---

- name: python check if exists
  command: python --version
  ignore_errors: yes
  register: python_present

- name: python | Install package
  apt: name=python state=latest
  become: yes
  become_user: root
  when: python_present is failed

- name: pip | Install package
  apt: name=python-pip state=latest
  become: yes
  become_user: root

- name: Install plyvel python module
  become: yes
  become_user: root
  pip:
    name: plyvel
    state: latest
    executable: pip
    extra_args: "{{ pip_extra_args | default('') }}"
    
- name: ensure NSRL directory exists
  file:
    path: "{{ NSRL_path }}"
    state: directory
  become: yes
  become_user: root

- name: Unarchive 
  unarchive:
    src: "{{ NSRL_zip_url }}"
    dest: "{{ NSRL_path }}"
    remote_src: yes
  become: yes
  become_user: root
